ghga-de/microservice-repository-template

- .github/workflows/dev_cd.yml
- migrate to official GitHub action for pushing to docker (this has already been reviewed at some time but must have been accidentally overwritten)
- in addition to the detailed commit version, we also release a container just tagged with the branch name
> update CD workflow

- .pylintrc
added __, id and db as good variable names to pylint
> Updated linter good names

- .mandatory_files
Title:
```
remove openapi yaml from mandatory files
```
Description:
```
As not all services have a RESTful API.
```
> remove openapi yaml from mandatory files

- .devcontainer/devcontainer.json
Shows a vertical line at 88 characters.
> show a vertical line at the intended line limit

- .pre-commit-config.yaml
```
updated pre-commit hooks to latest versions
```
> updated pre-commit hooks to latest versions

- scripts/license_checker.py
```
disable license checking for html and xml
```
> disable license checking for html and xml

- .pre-commit-config.yaml
```
automatically fix bad formatted json
```
```
Enable the `autofix` functionality of the `prettier_format_json` pre-commit hook.
```
> automatically fix bad formatted json

- .github/workflows/check_config_schema_and_example.yaml
- .github/workflows/check_db_migration_scripts.yaml
- .github/workflows/check_openapi_spec.yaml
- .github/workflows/unit_and_int_tests.yaml
```
Use ghga-de/gh-action-common in GitHub Actions
```
```
Avoids repeating boilerplate code in Github Action yaml files
```
> Use ghga-de/gh-action-common in GitHub Action workflows

- .mandatory_files
- .static_files
```
move `license_header.txt` to static file list
```
> license header static

- .devcontainer/.dev_config.yaml
- config_schema.json
- setup.cfg
```
update ghga-service-chassis-lib version
```
Description:
```
This fixes dependency resolutions errors.
```
> update ghga-service-chassis-lib version

- .pre-commit-config.yaml
Update black version because of incompatibilites with click
https://github.com/psf/black/issues/2964
> update black version

- .github/workflows/static_code_analysis.yaml
- .mypy.ini
- .pre-commit-config.yaml
- mypy.ini
- scripts/license_checker.py
Moved all mypy configs from Github Actions and Pre-Commit to a mypy.ini
> added mypy.ini

- .devcontainer/library-scripts/docker-in-docker-debian.sh
This updates the docker-in-docker script to the current version.
With the existing version of the script, dev containers did not start up properly on my MacBook.
> Update docker-in-docker-debian.sh to current version

- .static_files
> add .mypy.ini to static file list

- README.md
> fix template for converage badge

- scripts/get_config_schema_and_example.py
Kersten's changes from EKS
```
Updated get_config_schema_and_example.py
Co-authored-by: KerstenBreuer <kersten-breuer@outlook.com>
Co-authored-by: Moritz Hahn <Moritz.Hahn@uni-tuebingen.de>
```
> Updated get_config_schema_and_example

- .pre-commit-config.yaml
The chassis lib will be updated later.
> udate mypy version in pre-commit

- .gitignore
Files like `local.env` should be ignored as well.
> Ignore local env files

- .pre-commit-config.yaml
- pytest.ini
- scripts/license_checker.py
- setup.cfg
Adapt to the changes in the chassis lib in [PR78](https://github.com/ghga-de/ghga-service-chassis-lib/pull/78).
> Update license checker

- .devcontainer/docker-compose.yml
LocalStack v1 requires a small configuration change, see [what's changed](https://github.com/localstack/localstack/issues/6398).
> Update configuration for LocalStack v1

- .deprecated_files
- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- scripts/script_utils/cli.py
- scripts/update_config_docs.py
- scripts/update_openapi_docs.py
- scripts/update_template_files.py
- add default settings and Dockerfile CMD in the template
- fix deprecated files list
- the template update script can now run with the standard lib only
> Small improvements and fix deprecation list

- scripts/update_template_files.py
Also some refactoring was necessary.
> Automatically set the executable flag

- .devcontainer/Dockerfile
- .static_files
and added it to the static files.
> updated devcontainer docker base (GDEV-1598)

- .devcontainer/dev_install
- .devcontainer/devcontainer.json
- Adapt to updated schema of devcontainer.json
- Update list of extensions
> Update customizations in devcontainer.json

- .mandatory_files
- .static_files
Local modifications can be made in the requirements files.
> Make dev_install static

- Dockerfile
> fix docker container

- .devcontainer/dev_install
- .mandatory_files
- .static_files
Deleted a line of code that prevented git config to be injected into devcontainers
Move fastapi_app_location script from static to mandatory files
> Fix git config injection

- .github/workflows/dev_cd.yaml
Used for rebuilding containers if needed.
> Added manual run of dev_cd

- .deprecated_files
- .github/workflows/cd.yaml
- .github/workflows/dev_cd.yaml
- .mandatory_files
- .static_files
[GDEV-1827](https://jira.verbis.dkfz.de/browse/GDEV-1827)
> adjust dev_cd to trigger on new release

- .devcontainer/devcontainer.json
- .gitignore
- requirements-dev-common.txt
```
- include extension for using the cprofiler together with pytest
- results can be visualized using snakeviz
```
> configure for using cprofile during testing (GSI-108)

- .devcontainer/dev_install
```
Causing problems when pinning dependencies in
setup.cfg but not pinning in dev-requirements.txt.
```
> remove --upgrade for dev install (GSI-222)

- .static_files
- scripts/__init__.py
- scripts/update_all.py
- scripts/update_template_files.py
Simple python script to call all update logic in correct order and check if license header are up to date in one go
> One script to run them all

- .github/workflows/cd.yaml
- .static_files
Not sure if the changes work, please double-check
> Fix regex for CD and add update_all script as static file

- .deprecated_files
- .github/workflows/tests.yaml
- .static_files
Moreover, rename GitHub action.
> fix coverage collection (GSI-398)

- .devcontainer/devcontainer.json
- .mandatory_files
- .static_files
```
- details can be found here: https://github.com/devcontainers/features/tree/main/src/docker-outside-of-docker
- removed name from devcontainer json to make it static
```
>  docker outside of docker (GSI-414)

- .mandatory_files
was already in static files but also in mandatory files
> add Dockerfile to static files (GSI-457)

- .readme_template.md
- README.md
This is a follow-up patch to #177 which was incomplete.
> Fix test badge link target

- scripts/license_checker.py
> Ignore FASTQ and TSV files in license check

- .readme_generation/description.md
- .readme_generation/readme_template.md
- .readme_generation/template_overview.md
- README.md
- scripts/update_readme.py
```
Is only present on the template and automatically removed for relying service repos.
```
> add a template description (GSI-545)

- .devcontainer/dev_install
- Dockerfile
- scripts/list_outdated_dependencies.py
This fixes a few references to requirements files that were missed in the changes.
> Fix outdated requirements file refs

- scripts/check_license.py
- Remove wrongly formatted and unneeded yaml file from exclusion list (yaml files are excluded anyway)
- Slightly improve the recognition and normalization of line comments
> Fix license checker

- .readme_generation/design.md
- .readme_generation/readme_template.md
- README.md
- scripts/update_readme.py
Fix some typos and bad grammar in the README file. Also replace deprecated Pydantic method.
> Fix README and deprecated methods
