ghga-de/microservice-repository-template

.devcontainer/devcontainer.json
Title:
```
run dev_install automatically upon devcontainer start (GDEV-300)
```
Description:
```
Using the "postCreateCommand" in the .devcontainer config
to automatically run the dev_install script
```
=> added postCreateCommand (GDEV-300)

.devcontainer/dev_launcher
Title:
```
Fix ingestion of config params for dev_launcher script
```
Description:
```
The dev_launcher script passed the config yaml via a CLI option to the service.
This option no longer exists. Config parameters are now ingested via the
`.my_microservice.yaml` file in the `.devcontainer` dir.
```
=> dev config passing

.devcontainer/dev_launcher
The dev_launcher script passed the config yaml via a CLI option to the service.
This option no longer exists. Config parameters are now ingested via the
`.my_microservice.yaml` file in the `.devcontainer` dir.
=> Fix ingestion of config params for dev_launcher script

.devcontainer/devcontainer.json
```
show a vertical line at the intended line limit
```
```
Shows a vertical line at 88 characters.
```
=> show a vertical line at the intended line limit

.pylintrc
```
globally disable pylint's duplicate-code
```
```
This is behaving strangely sometimes and cannot be disabled on an individual basis:
https://github.com/PyCQA/pylint/issues/214
```
Before merging, let's discuss that first in a stand-up.
=> globally disable pylint's duplicate-code

setup.cfg
```
inherit dev deps from the ghga_service_chassis_lib
```
```
Inherit dev and testing dependencies from the ghga_service_chassis_lib.
Moreover, updated the ghga_service_chassis_lib to version 0.6.0.
```
Will work once the new version of the ghga_service_chassis_lib  is released.
=> inherit dev deps from the ghga_service_chassis_lib

.devcontainer/devcontainer.json, .devcontainer/license_header.txt, .mandatory_files, scripts/license_checker.py
```
fix automatic license inserter
```
```
Use custom file header from file for automatically inserting license headers into
empty files.
This custom file header file also becomes the source of truth for the license checker
script.
```
=> fix automatic license inserter

.github/workflows/dev_cd.yaml
The patch would enable arm64 builds to be built and pushed to Docker Hub. Mostly for developers working on ARM not having to run Docker with amd64 emulation. Would require some follow-up PRs on individual repos.
---
Message for Squash & Merge:
```
Add arm64/v8 Docker builds
```
=> Add arm64/v8 Docker builds

.devcontainer/docker-compose.yml
```
avoid port collisions (GDEV-450)
```
```
When running the .devcontainer environments of multiple service repositories using vscode
in parallel, port conflicts often occured.
This PR solves the problem by removing the explicit port bindings from docker compose.
```
=> avoid port collisions (GDEV-450)

.pre-commit-config.yaml, .pylintrc
```
adapt pylint & pre-commit settings (GDEV-749)
```
Description:
```
- pylint ignoring additional checks: unnecessary-ellipsis, super-init-not-called
- update black version in pre-commit to fix dependency issue
```
=> adapt pylint & pre-commit settings (GDEV-749)

.pylintrc
```
ingore unnecessary-pass in pylintrc
```
Description:
```
Because that caused problems e.g. when defining custom
exception classes by subclassing from building base exceptions.
```
=> ingore unnecessary-pass in pylintrc

.pylintrc
Previously, we have disabled pylint checks, however, we found solutions
to avoid the problems criticized by pylint.
=> re-introduce pass and __init__ checks (pylint)

.pylintrc
Previously, we have disabled pylint checks, however, we found solutions
to avoid the problems criticized by pylint.
=> re-introduce pass and __init__ checks (pylint) (#83)

.github/workflows/dev_cd.yaml
As discussed in the dev team meeting:
- main branch is now the source of truth for the
deployment to the "staging" environment
- prepare for retiring of the dev branch
- not part of this PR: CD pipeline for deploying to production
(will be added once needed)
Will delete dev branch once merged.
=> trigger dev CD from main instead of dev (GDEV-790)

.devcontainer/devcontainer.json
I suggest using the service name as the name of the dev container. This name is shown as window title and thereby helps to distinguish different instances of Visual Studio Code.
=> Let the dev container name be the service name

.mypy.ini, .pre-commit-config.yaml
When we run mypy via pre-commit, standalone in Docker or via GitHub action, we always use the same configuration `.mypy.ini`. 
This is generally a good idea. However, mypy can still give a different result when run via pre-commit. This is because pre-commit uses a separate virtual env which does not have all the dependencies we may use in the code. Therefore it cannot infer certain types and will be generally more relaxed.
This is bad because it does not catch all typing errors that we can get via the checks in GitHub. It can also lead to an unsolvable dilemma: When adding a "type: ignore", pre-commit will complain ("unused ignore"), and when removing it, GitHub will complain (incompatible types, inferred from dependencies not available in the pre-commit env).
We could make running mypy …
=> Improve mypy configuration for pre-commit (GDEV-807)

.github/workflows/static_code_analysis.yaml
- updated the pre-commit action
- skipped no-commit-to-branch pre-commint hook when running via github actions
=> fix no-commit-to-branch hook on main branch (GDEV-982)

.static_files, pytest.ini
Accounts for DeprecationWarning: The 'asyncio_mode' default value will change to 'strict' in future, please explicitly use 'asyncio_mode=strict' or 'asyncio_mode=auto' in pytest configuration file.
=> configure pytest to use strict asyncio_mode (GDEV-1004)

.gitignore
Avoid accidentally checking in desktop settings files from Mac or Windows.
=> Ignore Mac and Windows desktop settings

.devcontainer/dev_install
Avoid deprecation warning caused by a feature flag that has become the default in the Python 3.9 docker image we are using - see [release notes of pip 21.3](https://pip.pypa.io/en/stable/news/#v21-3).
=> Remove deprecated feature flag (now the default)

example_config.yaml, scripts/get_config_schema_and_example.py
The `print_example` command creates a duplicate trailing newline characters, because the YAML dump and the print function both add a newline. Therefore, the `example_config.yaml` file also needs two trailing newlines to pass the GitHub checks, because it is compared with the output of `print_example`. This problem is hard to spot, and you can't even save a YAML file with two trailing newlines in the default config of Visual Studio code.
I suggest fixing this by having the `print_example` function not output that additional empty line and removing the duplicate newline from the `example.config.yaml`. This makes the output of `print_example` also consistent with the output of `print_schema` which does not have that additional newline.
=> Fix duplicate trailing line feed in config

scripts/update_static_files.py
When creating a file that is new to the static files, check if its parent dir already exists if not create it.
=> create non-existing dirs when updating static files

scripts/update_template_files.py
Currently only works on directories, i.e.: `NotADirectoryError: [Errno 20] Not a directory: PosixPath('/workspace/.devcontainer/library-scripts/docker-in-docker-debian.sh')`
Added a check to correctly remove files.
=> Fix for deprecated file removal

.github/workflows/check_config_docs.yaml, .github/workflows/check_openapi_spec.yaml, .github/workflows/check_template_files.yaml, .github/workflows/dev_cd.yaml, .github/workflows/static_code_analysis.yaml, .github/workflows/unit_and_int_tests.yaml
Currently we get some deprecation warnings in the logs because of old versions of GitHub actions.
=> Update GitHub actions

.devcontainer/dev_install, .github/workflows/static_code_analysis.yaml, .github/workflows/unit_and_int_tests.yaml, .pre-commit-config.yaml, .static_files, README.md, requirements-dev.txt, scripts/license_checker.py, setup.cfg
This PR changes the microservice template so that dev-requirements are installed via a separate requirements-dev.txt file, instead of using the dev extra from the chassis lib or hexkit.
=> Add separate requirements file for development

.devcontainer/dev_install
Fix misleading comment and consistently use requirements files (these can then be changed without changing the dev-install script or GitHub actions). Also, upgrade the dev dependencies when running the script.
=> Fix misleading comment in dev_install

.devcontainer/dev_install
The `dev_install` script should install in editable mode (again). Currently it doesn't since there is no `-e` in the `requirements.txt` file.
=> Install in editable mode in dev_install script

.deprecated_files_ignore, .pylintrc, my_microservice/__main__.py, my_microservice/api/main.py, my_microservice/config.py, scripts/update_config_docs.py, setup.cfg
- Migrate from GHGA service chassis lib to GHGA service commons
- Update the pylint configuration to avoid a deprecation warning
- Improve the `update_config_docs` script so that it shows diffs (helpful to debug failing GitHub action)
=> Use service commons and update pylint configuration

requirements-dev-common.txt
```
- docker-py is a dependency of python-testcontainers
- moreover, added pytest-httpx plugin for request mocking
```
=> fix docker-py incompatibility with requests/urllib3 (GSI-110)

.github/workflows/cd.yaml
Currently the GHGA services are only built for x86_64/amd64 architectures. Not only does this limit the adoptability on more cost-efficient arm nodes, but also poses a problem for developers operating on arm cpus (such as newer MacBooks).
This can be fixed by adding the option platforms: linux/amd64,linux/arm64 to the docer/build-push-action.
This was already applied to [metadata-catalog](https://github.com/ghga-de/metadata-catalog/pull/45).
=> Support arm64 by using multi-platform builds

.ruff.toml, .static_files, scripts/update_config_docs.py, scripts/update_lock.py, scripts/update_openapi_docs.py, scripts/update_readme.py
While updating hexkit, it was decided that some of the rules from pydocstyle are impractical and to ignore them.
Including:
"D205", # blank-line-after-summary
"D400", # first doc line ends in period
"D401", # non-imperative-mood 
"D107", # missing docstring in __init__ function
Also removed setup.py from static files and included update_hook_revs.py. Somehow those changes got excluded from previous PRs.
=> Ignore ruff rules from pydocstyle

.github/workflows/cd.yaml, .pre-commit-config.yaml, .static_files, scripts/list_outdated_dependencies.py, scripts/script_utils/deps.py, scripts/script_utils/lock_deps.py, scripts/update_hook_revs.py, scripts/update_lock.py
This adds a script (`scripts/list_outdated_dependencies.py`) that is meant to:
- List outdated capped dependencies based on what is _specified_.
- When used with `--transitive`, list outdated transitive dependencies based on what is _pinned in the lock file_.
It works by obtaining the latest version of a package from PyPI and seeing whether that version satisfies the version range we have specified.
Uncapped dependencies should therefore always be omitted by this method.
For example, if we required hexkit like this:
`hexkit ~= 0.9.0`
and the latest version on PyPI is 0.10.x, then the script will see that 0.10.x is not contained within the specifier `~= 0.9.0` and flag it as outdated. 
If the specifier were uncapped, e.g. `hexkit >= 0.9.0`, then it would not be flagged as outdated because …
=> Script to check for outdated dependencies (GSI 371)

.coveragerc, .static_files, scripts/license_checker.py, tests/test_dummy.py
This PR adds a coverage configuration file that maps the site-packages location to the workspace location.
This removes the long leading path that otherwise appears in the coverage reports.
It also makes the dummy test access the core module so that we can see a coverage report in the template.
=> Add coverage config with source mapping

.description.md, Dockerfile, README.md
Rely only on the requirements.txt lock file for installing dependencies and do not install additional dependencies when installing the wheel, to make the build process completely reproducible. If a requirement is not contained in the lock file, this should be considered an error and make the service fail instead of being silently fixed by the pip install command.
=> Do not install additional requirements

scripts/update_config_docs.py
The move to pydantic v2 includes changing `BaseSettings` import from pydantic to pydantic_settings. The common scripts in the microservice template need to be agnostic in this regard to avoid forcing the pydantic v2 changes and disturbing current tickets or PRs. The only spot that has caused any issue in this regard is the return type annotation for the `get_config_class` function in `scripts/update_config_docs.py`. If we remove that annotation, we can remove the BaseSettings import completely and not have to worry about any workaround. 
The previous solution (workaround) had a minor flaw. While the mypy `type: ignore` was valid for repos that moved to pydantic v2, it would be seen as unused for any repos still on pydantic v1.
=> Remove BaseSettings return type annotation

.readme_template.md, README.md
This patch adjusts the test badge URL in the README template to match the new filename of the pytest workflow definition file (`tests.yaml`)
=> Adjust test badge URL to match new filename

.github/workflows/ci_workflow_dispatch.yaml
Currently the build action is not triggered on `workflow-dispatch` events due to the conditional (see our hacky dcs [branch](https://github.com/ghga-de/download-controller-service/blob/add-logging-for-integration-issues/.github/workflows/ci_workflow_dispatch.yaml)). Since we need to retrieve the latest tag in both cases, I would suggest extending it.
=> Fix conditional in build action

.github/workflows/ci_workflow_dispatch.yaml
Fixes brackets and variable in conditional. The name of the action is accessible with [`github.event_name`](https://docs.github.com/en/actions/learn-github-actions/contexts#github-contextl), e.g. `workflow_dispatch`. The variable [`github.action.event`](https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=auto_merge_disabled#pull_request) is its type, e.g. `labeled`.
=> Fix conditional in job

.devcontainer/docker-compose.yml, .github/workflows/check_config_docs.yaml, .github/workflows/check_openapi_spec.yaml, .github/workflows/check_pyproject.yaml, .github/workflows/check_readme.yaml, .github/workflows/check_template_files.yaml, .github/workflows/ci_release.yaml, .github/workflows/ci_workflow_dispatch.yaml, .github/workflows/static_code_analysis.yaml, .github/workflows/tests.yaml
- Remove obsolete docker hub version to avoid warning in logs
- Use canonical order of properties in GitHub actions
=> Remove obsolete docker hub version

.github/workflows/check_config_docs.yaml, .github/workflows/check_openapi_spec.yaml, .github/workflows/check_pyproject.yaml, .github/workflows/check_readme.yaml, .github/workflows/static_code_analysis.yaml
Run some of the tools under Python 3.12 on GitHub, because this might be a bit faster.
However, the main static code analysis should run on the same default Python version as locally, which is still Python 3.9. Otherwise there might be some discrepancies between the local and remote analysis, which we want to avoid.
=> Run scripts in GitHub under Python 3.12

.template/deprecated_files.txt
The script has been renamed to `check_license`, so the old name must be marked as deprecated.
=> Mark removed license checker script as deprecated

.github/workflows/ci_release.yaml, Dockerfile, Dockerfile.debian
This patch changes the template such that it contains two Dockerfiles:
1. `Dockerfile` which builds a runner container based on python-alpine
2. `Dockerfile.debian` which builds a runner container based on python-debian
Both images are pushed to Dockerhub, once with the tag suffix `-debian` once without (this makes use of the recently added support for "flavors" in PR https://github.com/ghga-de/gh-action-ci/pull/4).
The alpine Dockerfile has been tested on all currently deployed services to the extend that they start and fail due to missing configuration.
A separate PR will be opened at https://github.com/ghga-de/file-services-backend.
=> Enable default alpine and fallback debian docker image builds (GSI-876)

.devcontainer/devcontainer.json
Used the syntax found [here](https://github.com/microsoft/vscode-docs/blob/main/remote-release-notes/v1_85.md#opt-out-of-extensions) to remove the autopep8 extension for vs code.
The extension is automatically installed in the devcontainer by a feature included in the base image, and it conflicts with ruff. It's annoying to uninstall autopep8 + reload window every time you rebuild a devcontainer, so this is the solution.
=> Remove autopep8 vs code extension

lock/requirements-dev-template.in, lock/requirements-dev.txt
Saw the dependabot warning for `requests <2.32.4` on the DS Kit, so updating the minimum version req here.
=> Update `requests` version floor
